[workspace]
members = ["crates/bug-runtime", "crates/bug-windows"]
default-members = ["crates/bug-runtime"]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT"
rust-version = "1.97.1"
version = "2.0.0"

[workspace.dependencies]
mlua = { version = "0.12.0", default-features = false, features = ["lua54", "vendored"] }
png = { version = "0.18.1", default-features = false }
raw-window-handle = "0.6.2"
sdl2 = { version = "0.38.0", default-features = false, features = ["raw-window-handle"] }
windows = { version = "0.62.2", default-features = false, features = [
    "std",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Memory",
    "Win32_System_Threading",
    "Win32_UI_Controls",
    "Win32_UI_HiDpi",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }

[profile.release]
codegen-units = 1
lto = "thin"
panic = "abort"
strip = "symbols"
