[package]
name = "bug-windows"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
bug-runtime = { path = "../bug-runtime" }

[target.'cfg(windows)'.dependencies]
png.workspace = true
raw-window-handle.workspace = true
sdl2.workspace = true
windows.workspace = true

[build-dependencies]
embed-resource = "3.0.11"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"

[lints.clippy]
all = "deny"
